{% set name = "pybispectra" %}
{% set version = "1.2.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybispectra-{{ version }}.tar.gz
  sha256: 54326457d3c339833dc7fb8c225d68923c20766be36a0af923527a7998206970

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.0
    - matplotlib-base >=3.5
    - mne >=1.7
    - numba >=0.55
    - numpy >=1.21
    - scikit-learn >=1.0
    - scipy >=1.7

test:
  imports:
    - pybispectra
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pybispectra.readthedocs.io/
  summary: A Python signal processing package for computing spectral-domain and time-domain interactions using the bispectrum.
  dev_url: https://github.com/braindatalab/PyBispectra
  doc_url: https://pybispectra.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tsbinns
