{% set name = "pybispectra" %}
{% set version = "1.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybispectra-{{ version }}.tar.gz
  sha256: 8bd947dec464e658fbc9bafe23ec30d033e503a2a74c049f86aad3c823dc6407

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.0.0
    - matplotlib-base >=3.5.0
    - mne >=1.7
    - numba >=0.55.0
    - numpy >=1.21.2
    - scikit-learn >=1.0
    - scipy >=1.7.1

test:
  imports:
    - pybispectra
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pybispectra.readthedocs.io/
  summary: A Python signal processing package for computing spectral-domain and time-domain interactions using the bispectrum.
  dev_url: https://github.com/braindatalab/PyBispectra
  doc_url: https://pybispectra.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tsbinns
